<?php

use Hyva\Checkout\Magewire\Checkout\Payment\Method\PurchaseOrder;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var PurchaseOrder $magewire */
/** @var Escaper $escaper */

?>
<div class="col-span-6">
    <label class="block font-medium text-gray-700">
        <?= $escaper->escapeHtml(__('Social Security Number')) ?>

        <input wire:model.delay.750ms="socialSecurityNumber"
               type="text"
               class="block w-full
                      shadow-sm
                      border-gray-300 rounded-md"
        />
    </label>

    <?php if ($magewire->hasError('socialSecurityNumber')): ?>
        <p class="text-red-500 mt-4 text-sm">
            <?= $escaper->escapeHtml($magewire->getError('socialSecurityNumber')) ?>
        </p>
    <?php endif ?>
</div>
